### ISSUE TITLE
Steiner tree improvement

### ISSUE THREAD

**Issue by y-richie-y** [sg495/pauliopt#3]
At the moment the Steiner tree function create cycles:

Currently in the implementation, the Steiner tree contains nodes that need eliminating and the intermediate nodes are stored as edges, the added edges (`mst_branches`) are not necessarily disjoint.

https://github.com/sg495/pauliopt/blob/06c0178c93223733daea80f4829833a1f7a2bbe0/pauliopt/phase/phase_circuits.py#L79

Lets make the trees cycle free 😄

**Comment by ghost** [comment]
Hey @y-richie-y. I found your repository and I am excited at the prospect of contributing to it (I am fascinated by everything quantum computing related!). I am experienced in Python however I am new to the topic of the repository.  Is it possible for me to receive some guidance in order for me to best contribute to this repository? 

Thanks!

**Comment by y-richie-y** [comment]
@YuvalBogachev one easy thing to try is to add more gate options to 

https://github.com/sg495/pauliopt/blob/5e10a287af0656e45f6b08cc9f31d646d0cef11f/pauliopt/phase/phase_circuits.py#L373

**Comment by Aerylia** [comment]
Thanks! I think this can be closed now
